apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-myapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
